name: Test and build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: pnpm
      - run: |
          npm config set '@fortawesome:registry' '${{ secrets.FONTAWESOME_REGISTRY }}'
          npm config set '//harding.dev:23435/:_authToken' '${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}'
          pnpm install

      # TODO: code coverage, reporting, break these steps up
      - run: pnpm format
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm typecheck
      - run: pnpm build
